# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ChangePointsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChangePointsform(object):
    def setupUi(self, ChangePointsform):
        ChangePointsform.setObjectName("ChangePointsform")
        ChangePointsform.resize(332, 456)
        self.centralwidget = QtWidgets.QWidget(ChangePointsform)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 312, 370))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.changePointsBut = QtWidgets.QPushButton(self.centralwidget)
        self.changePointsBut.setObjectName("changePointsBut")
        self.verticalLayout_2.addWidget(self.changePointsBut)
        self.backBut = QtWidgets.QPushButton(self.centralwidget)
        self.backBut.setObjectName("backBut")
        self.verticalLayout_2.addWidget(self.backBut)
        ChangePointsform.setCentralWidget(self.centralwidget)

        self.retranslateUi(ChangePointsform)
        QtCore.QMetaObject.connectSlotsByName(ChangePointsform)

    def retranslateUi(self, ChangePointsform):
        _translate = QtCore.QCoreApplication.translate
        ChangePointsform.setWindowTitle(_translate("ChangePointsform", "Изменить города"))
        self.changePointsBut.setText(_translate("ChangePointsform", "Изменить"))
        self.backBut.setText(_translate("ChangePointsform", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChangePointsform = QtWidgets.QMainWindow()
    ui = Ui_ChangePointsform()
    ui.setupUi(ChangePointsform)
    ChangePointsform.show()
    sys.exit(app.exec_())
