# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/PriceListsForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PriceListsForm(object):
    def setupUi(self, PriceListsForm):
        PriceListsForm.setObjectName("PriceListsForm")
        PriceListsForm.resize(370, 223)
        self.centralwidget = QtWidgets.QWidget(PriceListsForm)
        self.centralwidget.setObjectName("centralwidget")
        self.startDate = QtWidgets.QDateEdit(self.centralwidget)
        self.startDate.setGeometry(QtCore.QRect(20, 30, 181, 28))
        self.startDate.setObjectName("startDate")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 131, 19))
        self.label_2.setObjectName("label_2")
        self.endDate = QtWidgets.QDateEdit(self.centralwidget)
        self.endDate.setGeometry(QtCore.QRect(20, 90, 181, 28))
        self.endDate.setObjectName("endDate")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 70, 151, 19))
        self.label_3.setObjectName("label_3")
        self.tourPriceLe = QtWidgets.QLineEdit(self.centralwidget)
        self.tourPriceLe.setGeometry(QtCore.QRect(20, 140, 181, 27))
        self.tourPriceLe.setObjectName("tourPriceLe")
        self.addPriceListBut = QtWidgets.QPushButton(self.centralwidget)
        self.addPriceListBut.setGeometry(QtCore.QRect(240, 30, 88, 27))
        self.addPriceListBut.setObjectName("addPriceListBut")
        self.backBut = QtWidgets.QPushButton(self.centralwidget)
        self.backBut.setGeometry(QtCore.QRect(240, 70, 88, 27))
        self.backBut.setObjectName("backBut")
        PriceListsForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PriceListsForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 370, 24))
        self.menubar.setObjectName("menubar")
        PriceListsForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PriceListsForm)
        self.statusbar.setObjectName("statusbar")
        PriceListsForm.setStatusBar(self.statusbar)

        self.retranslateUi(PriceListsForm)
        QtCore.QMetaObject.connectSlotsByName(PriceListsForm)

    def retranslateUi(self, PriceListsForm):
        _translate = QtCore.QCoreApplication.translate
        PriceListsForm.setWindowTitle(_translate("PriceListsForm", "Прайс листы"))
        self.label_2.setText(_translate("PriceListsForm", "Дата начала тура:"))
        self.label_3.setText(_translate("PriceListsForm", "Дата окончания тура:"))
        self.tourPriceLe.setPlaceholderText(_translate("PriceListsForm", "Стоимость тура"))
        self.addPriceListBut.setText(_translate("PriceListsForm", "Добавить"))
        self.backBut.setText(_translate("PriceListsForm", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PriceListsForm = QtWidgets.QMainWindow()
    ui = Ui_PriceListsForm()
    ui.setupUi(PriceListsForm)
    PriceListsForm.show()
    sys.exit(app.exec_())
