# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/ToursForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ShowTours(object):
    def setupUi(self, ShowTours):
        ShowTours.setObjectName("ShowTours")
        ShowTours.resize(685, 623)
        self.centralwidget = QtWidgets.QWidget(ShowTours)
        self.centralwidget.setObjectName("centralwidget")
        self.toursTable = QtWidgets.QTableWidget(self.centralwidget)
        self.toursTable.setGeometry(QtCore.QRect(20, 40, 471, 531))
        self.toursTable.setObjectName("toursTable")
        self.toursTable.setColumnCount(0)
        self.toursTable.setRowCount(0)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 10, 121, 19))
        self.label.setObjectName("label")
        self.deleteTourBut = QtWidgets.QPushButton(self.centralwidget)
        self.deleteTourBut.setGeometry(QtCore.QRect(510, 90, 161, 41))
        self.deleteTourBut.setObjectName("deleteTourBut")
        self.addTourBut = QtWidgets.QPushButton(self.centralwidget)
        self.addTourBut.setGeometry(QtCore.QRect(510, 40, 161, 41))
        self.addTourBut.setObjectName("addTourBut")
        self.changePointsBut = QtWidgets.QPushButton(self.centralwidget)
        self.changePointsBut.setGeometry(QtCore.QRect(510, 140, 161, 41))
        self.changePointsBut.setObjectName("changePointsBut")
        self.priceListsBut = QtWidgets.QPushButton(self.centralwidget)
        self.priceListsBut.setGeometry(QtCore.QRect(510, 190, 161, 41))
        self.priceListsBut.setObjectName("priceListsBut")
        self.backBut = QtWidgets.QPushButton(self.centralwidget)
        self.backBut.setGeometry(QtCore.QRect(510, 520, 161, 41))
        self.backBut.setObjectName("backBut")
        self.orderTourBut = QtWidgets.QPushButton(self.centralwidget)
        self.orderTourBut.setGeometry(QtCore.QRect(510, 240, 161, 41))
        self.orderTourBut.setObjectName("orderTourBut")
        self.infoBut = QtWidgets.QPushButton(self.centralwidget)
        self.infoBut.setGeometry(QtCore.QRect(510, 440, 161, 31))
        self.infoBut.setObjectName("infoBut")
        self.returnBut = QtWidgets.QPushButton(self.centralwidget)
        self.returnBut.setGeometry(QtCore.QRect(510, 480, 161, 31))
        self.returnBut.setObjectName("returnBut")
        self.tourInfoTe = QtWidgets.QTextEdit(self.centralwidget)
        self.tourInfoTe.setEnabled(True)
        self.tourInfoTe.setGeometry(QtCore.QRect(20, 40, 471, 531))
        self.tourInfoTe.setObjectName("tourInfoTe")
        self.showHotelsBut = QtWidgets.QPushButton(self.centralwidget)
        self.showHotelsBut.setGeometry(QtCore.QRect(510, 290, 161, 41))
        self.showHotelsBut.setObjectName("showHotelsBut")
        self.pointsDiagramBut = QtWidgets.QPushButton(self.centralwidget)
        self.pointsDiagramBut.setGeometry(QtCore.QRect(510, 340, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pointsDiagramBut.setFont(font)
        self.pointsDiagramBut.setObjectName("pointsDiagramBut")
        ShowTours.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ShowTours)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 685, 24))
        self.menubar.setObjectName("menubar")
        ShowTours.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ShowTours)
        self.statusbar.setObjectName("statusbar")
        ShowTours.setStatusBar(self.statusbar)

        self.retranslateUi(ShowTours)
        QtCore.QMetaObject.connectSlotsByName(ShowTours)

    def retranslateUi(self, ShowTours):
        _translate = QtCore.QCoreApplication.translate
        ShowTours.setWindowTitle(_translate("ShowTours", "Посмотреть туры"))
        self.toursTable.setSortingEnabled(True)
        self.label.setText(_translate("ShowTours", "Доступные туры:"))
        self.deleteTourBut.setText(_translate("ShowTours", "Удалить тур"))
        self.addTourBut.setText(_translate("ShowTours", "Добавить тур"))
        self.changePointsBut.setText(_translate("ShowTours", "Изменить города"))
        self.priceListsBut.setText(_translate("ShowTours", "Прайс листы"))
        self.backBut.setText(_translate("ShowTours", "Назад"))
        self.orderTourBut.setText(_translate("ShowTours", "Заказать тур"))
        self.infoBut.setText(_translate("ShowTours", "Инфо"))
        self.returnBut.setText(_translate("ShowTours", "Вернуть"))
        self.showHotelsBut.setText(_translate("ShowTours", "5-звездочные отели"))
        self.pointsDiagramBut.setText(_translate("ShowTours", "Диаграмма населенных пунктов"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ShowTours = QtWidgets.QMainWindow()
    ui = Ui_ShowTours()
    ui.setupUi(ShowTours)
    ShowTours.show()
    sys.exit(app.exec_())
