# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/TourOrderForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToursOrder(object):
    def setupUi(self, ToursOrder):
        ToursOrder.setObjectName("ToursOrder")
        ToursOrder.resize(319, 566)
        self.centralwidget = QtWidgets.QWidget(ToursOrder)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.tourStartDateCb = QtWidgets.QComboBox(self.centralwidget)
        self.tourStartDateCb.setObjectName("tourStartDateCb")
        self.verticalLayout.addWidget(self.tourStartDateCb)
        self.printPriceListBut = QtWidgets.QPushButton(self.centralwidget)
        self.printPriceListBut.setObjectName("printPriceListBut")
        self.verticalLayout.addWidget(self.printPriceListBut)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.tourEndDateLe = QtWidgets.QLineEdit(self.centralwidget)
        self.tourEndDateLe.setReadOnly(True)
        self.tourEndDateLe.setObjectName("tourEndDateLe")
        self.verticalLayout.addWidget(self.tourEndDateLe)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.tourPriceLe = QtWidgets.QLineEdit(self.centralwidget)
        self.tourPriceLe.setReadOnly(True)
        self.tourPriceLe.setObjectName("tourPriceLe")
        self.verticalLayout.addWidget(self.tourPriceLe)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.nameLe = QtWidgets.QLineEdit(self.centralwidget)
        self.nameLe.setObjectName("nameLe")
        self.verticalLayout.addWidget(self.nameLe)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.surnameLe = QtWidgets.QLineEdit(self.centralwidget)
        self.surnameLe.setObjectName("surnameLe")
        self.verticalLayout.addWidget(self.surnameLe)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.patronymicLe = QtWidgets.QLineEdit(self.centralwidget)
        self.patronymicLe.setObjectName("patronymicLe")
        self.verticalLayout.addWidget(self.patronymicLe)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.phoneLe = QtWidgets.QLineEdit(self.centralwidget)
        self.phoneLe.setObjectName("phoneLe")
        self.verticalLayout.addWidget(self.phoneLe)
        self.orderTourBut = QtWidgets.QPushButton(self.centralwidget)
        self.orderTourBut.setObjectName("orderTourBut")
        self.verticalLayout.addWidget(self.orderTourBut)
        self.backBut = QtWidgets.QPushButton(self.centralwidget)
        self.backBut.setObjectName("backBut")
        self.verticalLayout.addWidget(self.backBut)
        ToursOrder.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ToursOrder)
        self.statusbar.setObjectName("statusbar")
        ToursOrder.setStatusBar(self.statusbar)

        self.retranslateUi(ToursOrder)
        QtCore.QMetaObject.connectSlotsByName(ToursOrder)

    def retranslateUi(self, ToursOrder):
        _translate = QtCore.QCoreApplication.translate
        ToursOrder.setWindowTitle(_translate("ToursOrder", "Заказать тур"))
        self.label_2.setText(_translate("ToursOrder", "Выберите подходящее предложение:"))
        self.label_3.setText(_translate("ToursOrder", "Дата начала тура:"))
        self.printPriceListBut.setText(_translate("ToursOrder", "Вывести прайс-лист"))
        self.label_4.setText(_translate("ToursOrder", "Дата окончания тура:"))
        self.label_5.setText(_translate("ToursOrder", "Стоимость тура:"))
        self.label.setText(_translate("ToursOrder", "Имя:"))
        self.label_6.setText(_translate("ToursOrder", "Фамилия:"))
        self.label_7.setText(_translate("ToursOrder", "Отчество:"))
        self.label_8.setText(_translate("ToursOrder", "Телефон:"))
        self.orderTourBut.setText(_translate("ToursOrder", "Заказать"))
        self.backBut.setText(_translate("ToursOrder", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ToursOrder = QtWidgets.QMainWindow()
    ui = Ui_ToursOrder()
    ui.setupUi(ToursOrder)
    ToursOrder.show()
    sys.exit(app.exec_())
