# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/MainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(327, 345)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.allToursBut = QtWidgets.QPushButton(self.centralwidget)
        self.allToursBut.setGeometry(QtCore.QRect(90, 30, 141, 41))
        self.allToursBut.setObjectName("allToursBut")
        self.changeDataBut = QtWidgets.QPushButton(self.centralwidget)
        self.changeDataBut.setGeometry(QtCore.QRect(90, 100, 141, 41))
        self.changeDataBut.setObjectName("changeDataBut")
        self.exitBut = QtWidgets.QPushButton(self.centralwidget)
        self.exitBut.setGeometry(QtCore.QRect(90, 170, 141, 41))
        self.exitBut.setObjectName("exitBut")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 327, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Главное меню"))
        self.allToursBut.setText(_translate("MainWindow", "Все туры"))
        self.changeDataBut.setText(_translate("MainWindow", "Изменить данные"))
        self.exitBut.setText(_translate("MainWindow", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
