# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uis/NewTourForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TourCreateForm(object):
    def setupUi(self, TourCreateForm):
        TourCreateForm.setObjectName("TourCreateForm")
        TourCreateForm.resize(391, 271)
        self.centralwidget = QtWidgets.QWidget(TourCreateForm)
        self.centralwidget.setObjectName("centralwidget")
        self.tourNameLe = QtWidgets.QLineEdit(self.centralwidget)
        self.tourNameLe.setGeometry(QtCore.QRect(10, 10, 221, 27))
        self.tourNameLe.setObjectName("tourNameLe")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 141, 19))
        self.label.setObjectName("label")
        self.tourTypeCb = QtWidgets.QComboBox(self.centralwidget)
        self.tourTypeCb.setGeometry(QtCore.QRect(160, 60, 131, 27))
        self.tourTypeCb.setObjectName("tourTypeCb")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 211, 19))
        self.label_2.setObjectName("label_2")
        self.departPointCb = QtWidgets.QComboBox(self.centralwidget)
        self.departPointCb.setGeometry(QtCore.QRect(240, 100, 131, 27))
        self.departPointCb.setObjectName("departPointCb")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 181, 19))
        self.label_3.setObjectName("label_3")
        self.transpTypeCb = QtWidgets.QComboBox(self.centralwidget)
        self.transpTypeCb.setGeometry(QtCore.QRect(210, 140, 131, 27))
        self.transpTypeCb.setObjectName("transpTypeCb")
        self.createTourBut = QtWidgets.QPushButton(self.centralwidget)
        self.createTourBut.setGeometry(QtCore.QRect(250, 190, 121, 31))
        self.createTourBut.setObjectName("createTourBut")
        self.backBut = QtWidgets.QPushButton(self.centralwidget)
        self.backBut.setGeometry(QtCore.QRect(10, 190, 121, 31))
        self.backBut.setObjectName("backBut")
        TourCreateForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TourCreateForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 391, 24))
        self.menubar.setObjectName("menubar")
        TourCreateForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TourCreateForm)
        self.statusbar.setObjectName("statusbar")
        TourCreateForm.setStatusBar(self.statusbar)

        self.retranslateUi(TourCreateForm)
        QtCore.QMetaObject.connectSlotsByName(TourCreateForm)

    def retranslateUi(self, TourCreateForm):
        _translate = QtCore.QCoreApplication.translate
        TourCreateForm.setWindowTitle(_translate("TourCreateForm", "Создание тура"))
        self.tourNameLe.setPlaceholderText(_translate("TourCreateForm", "Введите название тура"))
        self.label.setText(_translate("TourCreateForm", "Выберите тип тура:"))
        self.label_2.setText(_translate("TourCreateForm", "Выберите место отправления:"))
        self.label_3.setText(_translate("TourCreateForm", "Выберите тип транспорта:"))
        self.createTourBut.setText(_translate("TourCreateForm", "Создать тур"))
        self.backBut.setText(_translate("TourCreateForm", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TourCreateForm = QtWidgets.QMainWindow()
    ui = Ui_TourCreateForm()
    ui.setupUi(TourCreateForm)
    TourCreateForm.show()
    sys.exit(app.exec_())
